out_dir: results/cora-gcn
metric_best: accuracy
metric_agg: argmax
wandb:
  use: False
  project: cora-GPS

dataset:
  format: PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: False # No Positional Encodings for MPNNs
  node_encoder_name: LapPE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False

posenc_LapPE:
  enable: False # No Positional Encodings for MPNNs
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 8
  layers: 2
  n_heads: 4
  raw_norm_type: none

posenc_RWSE:
  enable: False # No Positional Encodings for MPNNs
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm

train:
  mode: custom
  sampler: full_batch
  batch_size: 32
  eval_period: 5
  enable_ckpt: False

model:
  type: gnn # GNN instead of GraphGPS
  loss_fun: mse
  edge_decoding: dot


# gt:
#   layer_type: GCN+Transformer
#   layers: 4
#   n_heads: 4
#   dim_hidden: 64
#   dropout: 0.1
#   attn_dropout: 0.1
#   layer_norm: False
#   batch_norm: True

# Not using GraphGPS's Version
# gnn:
#   head: inductive_node
#   layers_pre_mp: 0
#   layers_post_mp: 3
#   dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
#   batchnorm: True
#   act: relu
#   dropout: 0.0
#   agg: mean
#   normalize_adj: False

gnn:
  layer_type: gcnconv
  layers_mp: 4
  dim_inner: 256
  batchnorm: True
  act: relu
  dropout: 0.0
  normalize_adj: False
  
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
